### ISSUE TITLE
Add support for 128Q device

### ISSUE THREAD

**Issue by Costya-Y** [QualiSystems/cloudshell-L1-rome#12]
Rome recently released 128Q version of their device, we need to add support for it.

**Comment by Costya-Y** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add support for 128Q Ports to Rome L1](https://trello.com/c/4EhuVQjy/9-add-support-for-128q-ports-to-rome-l1)

**Comment by saklar13** [comment]
added support in [4.1.4 release](https://github.com/QualiSystems/cloudshell-L1-w2w-rome/releases/tag/4.1.4)
